### ISSUE TITLE
[CLOSED] Buildout not working, No such file or directory: 'Installation for Developers'

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#18]
<a href="https://github.com/zopyx"><img src="https://avatars.githubusercontent.com/u/594239?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zopyx](https://github.com/zopyx)**
_Tuesday Oct 21, 2014 at 14:48 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.suite/issues/4_

---

bin/buildout -c dev.cfg
mr.developer: Queued 'ploneintranet.docconv.client' for checkout.
mr.developer: Queued 'ploneintranet.documentviewer' for checkout.
mr.developer: Queued 'ploneintranet.invitations' for checkout.
mr.developer: Queued 'ploneintranet.simplesharing' for checkout.
mr.developer: Queued 'ploneintranet.theme' for checkout.
mr.developer: Queued 'ploneintranet.workspace' for checkout.
mr.developer: Queued 'plonesocial.activitystream' for checkout.
mr.developer: Queued 'plonesocial.core' for checkout.
mr.developer: Queued 'plonesocial.messaging' for checkout.
mr.developer: Queued 'plonesocial.microblog' for checkout.
mr.developer: Queued 'plonesocial.network' for checkout.
mr.developer: Skipped checkout of existing package 'ploneintranet.docconv.client'.
mr.developer: Skipped checkout of existing package 'ploneintranet.invitations'.
mr.developer: Skipped checkout of existing package 'ploneintranet.documentviewer'.
mr.developer: Skipped checkout of existing package 'ploneintranet.simplesharing'.
mr.developer: Skipped checkout of existing package 'ploneintranet.theme'.
mr.developer: Skipped checkout of existing package 'ploneintranet.workspace'.
mr.developer: Skipped checkout of existing package 'plonesocial.core'.
mr.developer: Skipped checkout of existing package 'plonesocial.activitystream'.
mr.developer: Skipped checkout of existing package 'plonesocial.messaging'.
mr.developer: Skipped checkout of existing package 'plonesocial.microblog'.
mr.developer: Skipped checkout of existing package 'plonesocial.network'.
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/src/plonesocial.activitystream'
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/src/ploneintranet.theme'
no previously-included directories found matching 'prototype'
warning: no previously-included files found matching 'src/patterns.js'
warning: no files found matching '_' under directory 'src/ploneintranet/theme/theme/prototype'
warning: no previously-included files matching '_pyc' found anywhere in distribution
warning: no previously-included files matching '._.swp' found anywhere in distribution
warning: no previously-included files matching '._.swo' found anywhere in distribution
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/src/plonesocial.messaging'
warning: no directories found matching 'plonesocial'
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/src/ploneintranet.simplesharing'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/src/plonesocial.core'
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/src/plonesocial.microblog'
Develop: '/Users/ajung/sandboxes/ploneintranet.suite/.'
Traceback (most recent call last):
  File "/var/folders/pj/5vwbn0n53d9001wfkr308p3w0000gn/T/tmpZrM3bC", line 11, in <module>
    execfile('/Users/ajung/sandboxes/ploneintranet.suite/./setup.py')
  File "/Users/ajung/sandboxes/ploneintranet.suite/./setup.py", line 14, in <module>
    + '\n')
IOError: [Errno 2] No such file or directory: 'Installation for Developers'
While:
  Installing.
  Processing develop directory '/Users/ajung/sandboxes/ploneintranet.suite/.'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/ajung/.buildout/eggs/zc.buildout-1.6.3-py2.7.egg/zc/buildout/buildout.py", line 1852, in main
    getattr(buildout, command)(args)
  File "/Users/ajung/.buildout/eggs/zc.buildout-1.6.3-py2.7.egg/zc/buildout/buildout.py", line 480, in install
    installed_develop_eggs = self._develop()
  File "/Users/ajung/.buildout/eggs/zc.buildout-1.6.3-py2.7.egg/zc/buildout/buildout.py", line 720, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/Users/ajung/.buildout/eggs/zc.buildout-1.6.3-py2.7.egg/zc/buildout/easy_install.py", line 1195, in develop
    *args) == 0
AssertionError

**Comment by wengole** [comment]
<a href="https://github.com/adamcheasley"><img src="https://avatars.githubusercontent.com/u/42489?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adamcheasley](https://github.com/adamcheasley)**
_Tuesday Oct 21, 2014 at 15:13 GMT_

---

Looks like this may be related to this commit:
https://github.com/ploneintranet/ploneintranet.suite/commit/b86bd75dbc55888e3c31c218b6b7dc6296ae0d42

**Comment by wengole** [comment]
<a href="https://github.com/jcbrand"><img src="https://avatars.githubusercontent.com/u/683911?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcbrand](https://github.com/jcbrand)**
_Tuesday Oct 21, 2014 at 16:03 GMT_

---

Sorry about that. Fixed now.
