### ISSUE TITLE
AttributeError: adapters

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#19]
<a href="https://github.com/zopyx"><img src="https://avatars.githubusercontent.com/u/594239?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zopyx](https://github.com/zopyx)**
_Tuesday Oct 21, 2014 at 15:11 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.suite/issues/5_

---

Creating a Plone site with the Intranet extension profile gives me this:

Traceback (most recent call last):
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in **init**
    response=b)
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/Users/ajung/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/**init**.py", line 31, in notify
    subscriber(event)
  File "/Users/ajung/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/ajung/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/ajung/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters

**Comment by wengole** [comment]
<a href="https://github.com/davisagli"><img src="https://avatars.githubusercontent.com/u/49014?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davisagli](https://github.com/davisagli)**
_Tuesday Oct 21, 2014 at 15:32 GMT_

---

This is usually a symptom of an earlier error. Anything above this in the log?

**Comment by wengole** [comment]
<a href="https://github.com/do3cc"><img src="https://avatars.githubusercontent.com/u/147512?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [do3cc](https://github.com/do3cc)**
_Wednesday Oct 29, 2014 at 09:49 GMT_

---

The problem does not seem to exist with the version that is available today, I can install a plone site as described in the readme and it starts up flawless. Fresh installation
