### ISSUE TITLE
Inconsistent issue with robot tests (breaking jenkins)

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#203]
Getting weird failures from Jenkins in robot tests that don't happen on development checkouts:

```
==============================================================================
Workspace
==============================================================================
Alice can upload a file
2015-05-14 16:10:32,387 - plone.subrequest - ERROR - Error handling subrequest to http://localhost:55001/plone/@@activitystream.tile?network=1
Traceback (most recent call last):
  File "/app/ploneintranet/eggs/plone.subrequest-1.6.8-py2.7.egg/plone/subrequest/__init__.py", line 116, in subrequest
    traversed = request.traverse(path)
  File "/app/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 617, in traverse
    response.unauthorized()
  File "/app/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/HTTPResponse.py", line 756, in unauthorized
    raise Unauthorized, m
Unauthorized: You are not authorized to access this resource.
```

**Comment by mattss** [comment]
This doesn't happen in my OSX dev environment, but I've just managed to replicate it using docker and a ubuntu VM... so I don't think it is specific to Jenkins. /cc @gyst

**Comment by mattss** [comment]
Sample Jenkins output: http://jenkins.ploneintranet.net/job/clean.Ploneintranet.thorough.master.True/83/console

**Comment by mattss** [comment]
@gyst are you still using the docker setup with Plone Intranet?

**Comment by mattss** [comment]
Have spent much of my day on and off on this trying to debug in a docker environment. Still no idea what is happening. At some point during robot tests, we are getting unauthorised in a tile subrequest. I cannot comprehend why this happens on certain machines and not others, running exactly the same code.

**Comment by mattss** [comment]
Hopefully we can resolve this early next week!

**Comment by mattss** [comment]
This was a bug in the robot tests exposed by an upgrade to Firefox 38. Resolved by https://github.com/ploneintranet/ploneintranet/commit/2422f77feb666167f6f6e7629bc73aa0557ffa2f
