### ISSUE TITLE
AttributeError: Options instance has no attribute 'query_bool'

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#21]
<a href="https://github.com/macagua"><img src="https://avatars.githubusercontent.com/u/185395?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [macagua](https://github.com/macagua)**
_Friday Nov 21, 2014 at 22:47 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.suite/issues/13_

---

Hi guys 

When I try to build a instance, and show me the following error:

```
Installing 'collective.recipe.omelette'.
We have the distribution that satisfies 'collective.recipe.omelette==0.15'.
Version conflict while processing requirement zc.buildout (constrained to zc.buildout==1.6.3)
Getting required 'zc.buildout==1.6.3'
We have the distribution that satisfies 'zc.buildout==1.6.3'.
Version conflict while processing requirement setuptools (constrained to setuptools==0.6c11)
Getting required 'setuptools==0.6c11'
We have the distribution that satisfies 'setuptools==0.6c11'.
Installing 'z3c.recipe.scripts'.
Picked: z3c.recipe.scripts = 1.0.1
Version conflict while processing requirement setuptools (constrained to setuptools==0.6c11)
Getting required 'setuptools==0.6c11'
We have the distribution that satisfies 'setuptools==0.6c11'.
Version conflict while processing requirement zc.buildout>=1.5.0 (constrained to zc.buildout==1.6.3)
Getting required 'zc.buildout==1.6.3'
We have the distribution that satisfies 'zc.buildout==1.6.3'.
While:
  Installing.
  Getting section scripts.
  Initializing section scripts.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/macagua/.buildout/eggs/zc.buildout-2.2.5-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/macagua/.buildout/eggs/zc.buildout-2.2.5-py2.7.egg/zc/buildout/buildout.py", line 510, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/macagua/.buildout/eggs/zc.buildout-2.2.5-py2.7.egg/zc/buildout/buildout.py", line 1098, in __getitem__
    options._initialize()
  File "/home/macagua/.buildout/eggs/zc.buildout-2.2.5-py2.7.egg/zc/buildout/buildout.py", line 1202, in _initialize
    self.initialize()
  File "/home/macagua/.buildout/eggs/zc.buildout-2.2.5-py2.7.egg/zc/buildout/buildout.py", line 1211, in initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/macagua/.buildout/eggs/z3c.recipe.scripts-1.0.1-py2.7.egg/z3c/recipe/scripts/scripts.py", line 39, in __init__
    self.include_site_packages = options.query_bool(
AttributeError: Options instance has no attribute 'query_bool'
```

Any Idea?

**Comment by ale-rt** [comment]
The original issue has been closed yesterday:
- https://github.com/ploneintranet/ploneintranet.suite/issues/13
