### ISSUE TITLE
without a running solr no plone instance can be created

### ISSUE THREAD

**Issue by clamor** [ploneintranet/ploneintranet#795]
The buildout process went fine, supervisor started the zeo cluster but creation of a plone instance produced the "AttributeError: adapters" below. Reason was that there was no java installed and solr did not get started. Some hint in the docs that java is a prerequisite would be nice.

---

2015-09-09T15:07:36 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in **init**
    response=b)
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/home/vagrant/ploneintranet/eggs/zope.event-3.5.2-py2.7.egg/zope/event/**init**.py", line 31, in notify
    subscriber(event)
  File "/home/vagrant/ploneintranet/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/vagrant/ploneintranet/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/vagrant/ploneintranet/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
## AttributeError: adapters

2015-09-09T15:07:42 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in **init**
    response=b)
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/home/vagrant/ploneintranet/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/home/vagrant/ploneintranet/eggs/zope.event-3.5.2-py2.7.egg/zope/event/**init**.py", line 31, in notify
    subscriber(event)
  File "/home/vagrant/ploneintranet/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/vagrant/ploneintranet/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/vagrant/ploneintranet/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters

**Comment by pilz** [comment]
Related to #478
