### ISSUE TITLE
Creating new Plone site fails with AttributeError

### ISSUE THREAD

**Issue by witekdev** [ploneintranet/ploneintranet#833]
Hi all,

I'm trying to setup an instance of Plone Intranet.
When trying to add a new site I get an AttributeError: adapters 
The traceback is here:
pastie.org/10471461

I followed the quickstart instructions, using the steps of section (b) Manual OS preparation:
http://docs.ploneintranet.org/installation/quickstart.html 

Running "make test-norobot" resulted in: 705 tests passed and 1 error due to:
"Solr Test Instance could not be started"
Relevant traceback:
http://pastie.org/10471464

I'm on Ubuntu 12.04. Happy to provide more details of my setup if need be..
Thanks!

**Comment by witekdev** [comment]
Here is a more detailed traceback: 

```
015-10-10 16:29:23 ERROR Zope.SiteErrorLog 1444487363.860.62405567801 http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 257, in __call__
  Module Products.CMFPlone.factory, line 103, in addPloneSite
  Module Products.GenericSetup.tool, line 374, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plone.app.contenttypes:plone-content
  Module Products.GenericSetup.tool, line 1268, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1113, in _doRunImportStep
   - __traceback_info__: plone.app.contenttypes--plone-content
  Module plone.app.contenttypes.setuphandlers, line 332, in step_import_content
  Module plone.app.contenttypes.setuphandlers, line 172, in create_frontpage
  Module plone.app.contenttypes.setuphandlers, line 92, in addContentToContainer
  Module OFS.ObjectManager, line 359, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module Products.CMFCore.CMFCatalogAware, line 262, in handleContentishEvent
  Module Products.CMFCore.CMFCatalogAware, line 188, in notifyWorkflowCreated
  Module Products.CMFCore.WorkflowTool, line 289, in notifyCreated
  Module Products.CMFCore.WorkflowTool, line 639, in _reindexWorkflowVariables
  Module Products.CMFCore.CMFCatalogAware, line 103, in reindexObjectSecurity
  Module collective.indexing.monkey, line 89, in unrestrictedSearchResults
  Module collective.indexing.queue, line 39, in processQueue
  Module collective.indexing.queue, line 165, in process
  Module ploneintranet.search.solr.indexers, line 286, in reindex
  Module ploneintranet.search.solr.indexers, line 277, in index
  Module ploneintranet.search.solr.indexers, line 229, in _get_data
  Module ploneintranet.search.solr.indexers, line 258, in _solr
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module ploneintranet.search.solr.adapters, line 25, in connection
  Module scorched.connection, line 242, in __init__
  Module scorched.connection, line 253, in init_schema
EnvironmentError: Couldn't retrieve schema document - status code 404
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /solr/core1/schema. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small><
</body>
</html>
2015-10-10 16:29:23 ERROR txn.139835773503232 Failed to abort resource manager: <collective.indexing.transactions.QueueTM object at 0x780f808>
Traceback (most recent call last):
  File "/home/witek/.buildout/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 503, in abort
    rm.abort(self)
  File "/home/witek/.buildout/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/transactions.py", line 63, in tpc_abort
    self.queue.abort()
  File "/home/witek/.buildout/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/queue.py", line 182, in abort
    for name, util in sm.getUtilitiesFor(IIndexQueueProcessor):
  File "/home/witek/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 172, in getUtilitiesFor
    for name, utility in self.utilities.lookupAll((), interface):
AttributeError: utilities
2015-10-10 16:29:23 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/home/witek/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/home/witek/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/home/witek/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/home/witek/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/BaseRequest.py", line 220, in close
    notify(EndRequestEvent(None, self))
  File "/home/witek/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/home/witek/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/witek/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/witek/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters
```

**Comment by witekdev** [comment]
I updated my java from 6 to 8, nuked the site and reinstalled, it works now.

Originally my java was:
java version "1.6.0_36"
OpenJDK Runtime Environment (IcedTea6 1.13.8) (6b36-1.13.8-0ubuntu1~12.04)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

Now is:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Note: I still get the "EnvironmentError: Solr Test Instance could not be started" when running "make test-norobot"
