### ISSUE TITLE
Creating a new site @@plone-adsite

### ISSUE THREAD

**Issue by odalton** [ploneintranet/ploneintranet#845]
Hi I have installed _ploneintranet_ but cant get past create a new Plone add new site page.
From this url http://localhost:8080/@@plone-addsite?site_id=Plone I click on the create Plone site btn and get the following console and on browser errors.

_browser output:_

```
Module ZPublisher.Publish, line 249, in publish_module_standard
Module ZPublisher.Publish, line 197, in publish
Module zope.event, line 31, in notify
Module zope.component.event, line 24, in dispatch
Module zope.component._api, line 136, in subscribers
Module zope.component.registry, line 321, in subscribers
```

_console output:_

```
2015-10-17 08:12:03 INFO GenericSetup.types 'Event' type info imported.
2015-10-17 08:12:03 INFO Products.GenericSetup.tool Applying main profile profile-plone.app.contenttypes:plone-content
2015-10-17 08:12:03 INFO GenericSetup.rolemap Role / permission map imported.
2015-10-17 08:12:03 INFO ploneintranet.search.solr.adapters Connecting to Solr on http://0.0.0.0:8983/solr/core1
2015-10-17 08:12:03 INFO requests.packages.urllib3.connectionpool Starting new HTTP connection (1): 0.0.0.0
2015-10-17 08:12:03 ERROR Zope.SiteErrorLog 1445040723.590.277620646143 http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 257, in __call__
  Module Products.CMFPlone.factory, line 103, in addPloneSite
  Module Products.GenericSetup.tool, line 374, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plone.app.contenttypes:plone-content
  Module Products.GenericSetup.tool, line 1268, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1113, in _doRunImportStep
   - __traceback_info__: plone.app.contenttypes--plone-content
  Module plone.app.contenttypes.setuphandlers, line 332, in step_import_content
  Module plone.app.contenttypes.setuphandlers, line 172, in create_frontpage
  Module plone.app.contenttypes.setuphandlers, line 92, in addContentToContainer
  Module OFS.ObjectManager, line 359, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module Products.CMFCore.CMFCatalogAware, line 262, in handleContentishEvent
  Module Products.CMFCore.CMFCatalogAware, line 188, in notifyWorkflowCreated
  Module Products.CMFCore.WorkflowTool, line 289, in notifyCreated
  Module Products.CMFCore.WorkflowTool, line 639, in _reindexWorkflowVariables
  Module Products.CMFCore.CMFCatalogAware, line 103, in reindexObjectSecurity
  Module collective.indexing.monkey, line 89, in unrestrictedSearchResults
  Module collective.indexing.queue, line 39, in processQueue
  Module collective.indexing.queue, line 165, in process
  Module ploneintranet.search.solr.indexers, line 286, in reindex
  Module ploneintranet.search.solr.indexers, line 277, in index
  Module ploneintranet.search.solr.indexers, line 229, in _get_data
  Module ploneintranet.search.solr.indexers, line 258, in _solr
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module ploneintranet.search.solr.adapters, line 25, in connection
  Module scorched.connection, line 242, in __init__
  Module scorched.connection, line 249, in init_schema
  Module scorched.connection, line 65, in request
  Module requests.sessions, line 465, in request
  Module requests.sessions, line 573, in send
  Module requests.adapters, line 415, in send
ConnectionError: ('Connection aborted.', error(61, 'Connection refused'))
2015-10-17 08:12:03 ERROR txn.4497956864 Failed to abort resource manager: <collective.indexing.transactions.QueueTM object at 0x10b13c8d8>
Traceback (most recent call last):
  File "/Users/oliver/.buildout/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 503, in abort
    rm.abort(self)
  File "/Users/oliver/.buildout/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/transactions.py", line 63, in tpc_abort
    self.queue.abort()
  File "/Users/oliver/.buildout/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/queue.py", line 182, in abort
    for name, util in sm.getUtilitiesFor(IIndexQueueProcessor):
  File "/Users/oliver/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 172, in getUtilitiesFor
    for name, utility in self.utilities.lookupAll((), interface):
AttributeError: utilities
2015-10-17 08:12:03 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/Users/oliver/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/Users/oliver/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/Users/oliver/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/Users/oliver/.buildout/eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/BaseRequest.py", line 220, in close
    notify(EndRequestEvent(None, self))
  File "/Users/oliver/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/oliver/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/oliver/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/oliver/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters
```

**Comment by odalton** [comment]
The issue was that solr was not running which was meant to start when you run bin/supervisord.  The resolution was to run bin/solr-instance start
