### ISSUE TITLE
Troubles creating new Site 

### ISSUE THREAD

**Issue by fgrcon** [ploneintranet/ploneintranet#901]
Following instructions at https://docs.ploneintranet.org/installation/development.html  (stepwise procedure without docker)  I succeeded until creating new plone site. (Simple or advanced selecting  different packages to install) I always end up with:

```
2016-07-28T15:11:59 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/usr/local/_eggs/Zope2-2.13.23-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/usr/local/_eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/usr/local/_eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/usr/local/_eggs/Zope2-2.13.23-py2.7.egg/ZPublisher/BaseRequest.py", line 220, in close
    notify(EndRequestEvent(None, self))
  File "/usr/local/_eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/usr/local/_eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/usr/local/_eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/usr/local/_eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters
```

**Update:**   

Selecting advanced mode and deselecting all packages : allowed to create the site. then activating addons one by one:  

**Products.CMFPlacefulWorkflow:**

```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 213, in __call__
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
__traceback_info__: ('Products.CMFPlacefulWorkflow',)
Module Products.GenericSetup.tool, line 378, in runAllImportStepsFromProfile
__traceback_info__: profile-Products.CMFPlacefulWorkflow:CMFPlacefulWorkflow
Module Products.GenericSetup.tool, line 1310, in _runImportStepsFromContext
Module Products.GenericSetup.tool, line 1146, in _doRunImportStep
__traceback_info__: placeful_workflow
Module Products.CMFPlacefulWorkflow.exportimport.workflow_policies, line 157, in importWorkflowPolicies
Module Products.GenericSetup.utils, line 853, in importObjects
__traceback_info__: portal_placeful_workflow
Module Products.GenericSetup.utils, line 849, in importObjects
__traceback_info__: portal_placeful_workflow/intranet
Module Products.GenericSetup.utils, line 512, in _importBody
Module Products.CMFCore.exportimport.workflow, line 61, in _importNode
Module Products.CMFPlacefulWorkflow.exportimport.workflow_policies, line 124, in _initChains
Module <string>, line 12, in setChain
Module AccessControl.requestmethod, line 70, in _curried
Module Products.CMFPlacefulWorkflow.DefaultWorkflowPolicy, line 278, in setChain
ValueError: 'Document' is not a valid portal type.

```

*_Plone Intranet: Suite,  collective.externaleditor default: as well as importing  testcontent via portal setup end width: *_

```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 213, in __call__
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
__traceback_info__: ('ploneintranet.suite',)
Module Products.GenericSetup.tool, line 378, in runAllImportStepsFromProfile
__traceback_info__: profile-ploneintranet.suite:default
Module Products.GenericSetup.tool, line 1310, in _runImportStepsFromContext
Module Products.GenericSetup.tool, line 1146, in _doRunImportStep
__traceback_info__: plone.app.registry
Module plone.app.registry.exportimport.handler, line 47, in importRegistry
Module plone.app.registry.exportimport.handler, line 92, in importDocument
Module plone.app.registry.exportimport.handler, line 371, in importRecords
Module plone.app.registry.exportimport.handler, line 240, in importRecord
Module plone.supermodel.utils, line 122, in elementToValue
Module plone.supermodel.utils, line 134, in elementToValue
Module zope.schema._field, line 322, in fromUnicode
Module zope.schema._bootstrapfields, line 183, in validate
Module zope.schema._field, line 338, in _validate
ConstraintNotSatisfied: (u'Image', '')
```

probably related to https://github.com/ploneintranet/ploneintranet/issues/888
Any hints ? 

I  really would like to have a closer look into this promising approach. 
Btw: Archetypes still part of the suite?, I would have thought about plone.app.contenttypes to make things easier?

**Comment by fgrcon** [comment]
My first Steps to first success:
-  bin/zeo start
-  bin/instance start
-  bin/instance2 start
-  bin/solr-instance start  <---- I missed this 
-  Create new site (without checking advanced)
-  activate Intranet Suite                       <----    (now also p.a.contenttypes are here  :-) )
-  Import  Testdata via portal setup as documented.
