### ISSUE TITLE
port 8080 not working

### ISSUE THREAD

**Issue by weelDaw** [ploneintranet/ploneintranet#915]
quaive/ploneintranet-deploy# ./bin/supervisorctl status

celery                           STARTING
flower                           RUNNING   pid 7858, uptime 0:29:46
instance                         RUNNING   pid 16497, uptime 0:00:03
instance2                        STARTING
solr                             RUNNING   pid 7856, uptime 0:29:46
zeo                              RUNNING   pid 7855, uptime 0:29:46

quaive/ploneintranet-deploy# bin/instance fg

2020-04-01 15:07:30 INFO ZServer HTTP server started at Wed Apr  1 15:07:30 2020
        Hostname: 0.0.0.0
        Port: 8080
2020-04-01 15:07:30 CRITICAL Zope A user was not specified to setuid to; fix this to start as root (change the effective-user directive in zope.conf)
Traceback (most recent call last):
  File "/home/quaive/ploneintranet-deploy/parts/instance/bin/interpreter", line 394, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 87, in prepare
    self.dropPrivileges()
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 224, in dropPrivileges
    return dropPrivileges(self.cfg)
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 383, in dropPrivileges
    raise ZConfig.ConfigurationError(msg)
ZConfig.ConfigurationError: A user was not specified to setuid to; fix this to start as root (change the effective-user directive in zope.conf)

**Comment by ale-rt** [comment]
Are you starting the instance as root?

> ZConfig.ConfigurationError: A user was not specified to setuid to; fix this to start as root (change the effective-user directive in zope.conf)

if yes you should specify the `effective-user=$REGULAR_USERNAME` in your buildout, rerun buildout and try `./bin/instance fg` once again

**Comment by weelDaw** [comment]
Hi @ale-rt , here is another error.

quaive@ubuntu:~/ploneintranet-deploy$ bin/instance fg

Traceback (most recent call last):
  File "/home/quaive/ploneintranet-deploy/parts/instance/bin/interpreter", line 394, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 85, in prepare
    self.setupServers()
  File "/home/quaive/ploneintranet-deploy/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 220, in setupServers
    % (server.servertype(),e[1]))
ZConfig.ConfigurationError: There was a problem starting a server of type "HTTPServer". This may mean that your user does not have permission to bind to the port which the server is trying to use or the port may already be in use by another application. (Address already in use)

**Comment by weelDaw** [comment]
I've already solved the issue. By changing ownership of ploneintranet-deploy to my user quaive and set my user quaive as sudoer.


Thanks, :)

**Comment by ale-rt** [comment]
> set my user quaive as sudoer.

This should not be needed but good you have something you can work on :)
